version: '3.3'
services:
    database:
        container_name: openelisglobal-database 
        image: postgres:9.5
        ports:
            - "5432:5432"
        restart: always
        env_file:
            - ./volume/database/database.env
        volumes:
              # preserves the database between containers
             - db-data:/var/lib/postgresql/data                
              # files here will run on install
             - ./volume/database/dbInit:/docker-entrypoint-initdb.d
        healthcheck:
            test: [ "CMD", "pg_isready", "-q", "-d", "clinlims", "-U", "clinlims" ]
            timeout: 45s
            interval: 10s
            retries: 10 
                       
volumes:
  db-data:
       
    
